- distro/adaptation/archlinux
- distro/adaptation/centos
- distro/adaptation/fedora
- distro/adaptation/opensuse
- distro/adaptation/ubuntu
CentOS and Fedora have a lot in common. But when add new packets, we may miss some dependence or add duplicated lines due to un-sorted file.
So I sorted all the files and removed duplicate lines.
Thanks
Hangbin
> distro/adaptation: sort and remove duplicate lines

- distro/adaptation/oracle
- distro/installer/oracle
- lib/detect-system.sh
- lib/install.sh
These modifications add initial Oracle Linux support.
Verified with a few tests (hackbench, unixbench) on Oracle Linux 6.9.
make install, lkp install, lkp split-job, lkp run, lkp result work fine.
> Add initial Oracle Linux support

- pack/stress-ng
Looks like the file was copied from tests/stress-ng. It should be
replaced.
Signed-off-by: Shi Xiaohai <xiaohai.sxh@alibaba-inc.com>
> stress-ng: incorrect pack/stress-ng file

- sbin/make.cross
gcc 8.1.0 for riscv is named riscv64, so override the default gcc_arch.
Signed-off-by: Deepa Dinamani <deepa.kernel@gmail.com>
> sbin/make.cross: use proper gcc_arch for ARCH=riscv

- repo/linux/rgushchin
Add my private kernel.org tree for cgroup and bpf development.
Signed-off-by: Roman Gushchin <guro@fb.com>
> repo: add own kernel tree for cgroup and bpf devel/testing

- bin/run-local
- bin/run-local.sh
- doc/lkp-howto.md
'run-local' and 'run-local.sh' usage message says that they support
'--dry-run' option but they don't.  This commit fixes the usage
messages.
Signed-off-by: SeongJae Park <sj38.park@gmail.com>
> run-local: Remove '--dry-run' option from usage message

- stats/mpstat
the previous method fails if the hostname contains 'a-b-c' like below:
~/workspace/lkp/lkp-tests$ head ../github-17/mpstat
Linux 4.9.112-32.el7.x86_64 (ip-10-22-2-38.us-west-2.compute.internal) 2018-09-18 	_x86_64_	(2 CPU)
07:31:09     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal %guest  %gnice   %idle
Fixes: #17
Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
> stats/mpstat: update new match method

- distro/adaptation/centos
- distro/adaptation/fedora
Quite sure that libgcc.686 was just a typo, forgetting the i.
Also, python-setuptools seems to suffice for the python-pkg-resources dependency on Fedora and CentOS
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> Fix adaptations for libhugetlbfs on centos/fedora

- sbin/make.cross
Users may want to install 0day tool chain into a custom location,
this patch makes sure we honor the user configuration if it's
present.
Signed-off-by: Leandro Dorileo <leandro.maciel.dorileo@intel.com>
> make.cross: allow user to configure GCC_INSTALL_PATH

- repo/linux/pcmoore-selinux
- repo/linux/selinux
- repo/linux/users-pcmoore-selinux
The selinux mailing list has moved to selinux@vger.kernel.org, so
update its address.  Drop two obsolete infradead git repos.
Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
> repo/linux: update selinux mailing list, drop obsolete git repos

- repo/linux/martineau
> repo: add build success notification for martineau

- Makefile
It adds TARGET_DIR_BIN to make it compatible for cross compilation
for other Linux distro such as Yocto.
Signed-off-by: Ankit Navik <ankit.tarot@gmail.com>
> Makefile: Adds TARGET_DIR_BIN variable

- repo/sparse/sparse
Currently lkp-tests uses for Sparse the semi-private repository
I have on github to share experimental branches.
Normally, I keep the master branch on this repository in sync
with the official repository on kernel.org but I think it would
be better for lkp-tests to use the official repository.
Signed-off-by: Luc Van Oostenryck <luc.vanoostenryck@gmail.com>
> use Sparse's official repository on kernel.org

- distro/adaptation/debian
- distro/adaptation/ubuntu
The bsdtar binary package has been replaced with the libarchive-tools
package in recent Debian and Ubuntu releases. For some time, the bsdtar
package was a transitional package that depended on the libarchive-tools
package but now the bsdtar package has been completely removed.
The libarchive-tools package does not exist in some currently supported
older releases such as Ubuntu 16.04 LTS so a simple adaptation is not
possbile as `lkp install` will fail on those releases. Instead, make use
of apt's regex support to install "bsdtar|libarchive-tools". It installs
both packages where they both exist (this is fine) and only installs the
one that exists where the other isn't available.
Tested on Ubuntu Eoan, Ubuntu 19.10, Ubuntu 19.04 LTS, Ubuntu 18.04 LTS,
Ubuntu 16.04 LTS, Debian Sid, and …
> distro/adaptation: Adjust for renamed bsdtar package

- distro/adaptation-pkg/debian
- distro/adaptation-pkg/ubuntu
- distro/adaptation/debian
- distro/adaptation/ubuntu
A set of fixes needed to run various tests on newer Debian and Ubuntu releases. Most are distro package name adaptations but one is a fix for a `makepkg` adaptation.
> Miscellaneous fixes for recent Debian and Ubuntu releases

- repo/linux/martineau
Modify repo set up to send me build results even if I'm not the author or committer.
I haven't found documentation for the repo/linux/* file format - is there any you can share?
Is it possible to only build certain branches? Or to have multiple configurations for the same repository that email different addresses for different branches?
> repo: add mail cc for martineau

- repo/linux/mptcp
This adds a build for the MPTCP development repository. I'm not sure what the "subsystems" section does, is anything else required to correctly add mptcp?
> Add mptcp development repository

- repo/linux/mptcp
> repo/linux/mptcp: Only build export branch

- repo/linux/android-common
I can get all reports through the mailing list and don't need to be copied
directly.
> repo/linux/android-common: No longer cc groeck@ directly

- repo/linux/chrome-os
Do not copy individual engineers on build problems; only send to the group.
Copy groeck@ directly on all reports.
> repo/linux/chrome-os: Do not copy individual engineers

- repo/linux/mptcp
Notify build success for export branch and list all project maintainers as owners.
> MPTCP updates for notifications

- repo/linux/mptcp
We've confirmed that our build configuration is working for the expected branch, so we don't need the success email any more.
> repo/linux/mptcp: Turn off build success notification

- repo/linux/derkling
- repo/linux/linux-pb
I do not have anymore access to the linux-pb repo, let's remove it.
Update also info related to my other github based repo.
Cc: Philip Li <philip.li@intel.com>
Cc: Dietmar Eggemann <dietmar.eggemann@arm.com>
Signed-off-by: Patrick Bellasi <patrick.bellasi@matbug.net>
> repo/linux: Update derkling's repos

- distro/installer/archlinux
- lib/install.sh
Using `lkp install` on ArchLinux distributions use the unmaintained package `yaourt`. I changed it with `yay` which is a almost equals substitute.
> lkp install on Archllinux: use yay instead yaourt

- distro/adaptation/archlinux
- distro/adaptation/fedora
The libarchive13 package is named libarchive on fedora and archlinux
> distro/adaptation: add libarchive to fedora and archlinux

- distro/installer/archlinux
- lib/install.sh
`yay  -Sy <pkg>` reinstalls  `<pkg>` if already present and updated, the flag `--needed` will prevent useless operations.
> Archlinux: yay won't reinstall updated pkgs anymore

- distro/depends/mpstat
- monitors/mpstat
Use pkill instead of kill to eliminate 'No such process' message if the
process has already been killed.
> mpstat: eliminate 'No such process' message

- distro/adaptation/debian
- distro/adaptation/ubuntu
The distro/adaptation/{debian,ubuntu} files are updated to avoid installation problem.
(corrected version of (https://github.com/intel/lkp-tests/pull/98) )
- add `bsdtar: libarchive-tools`;
- add docs-comment at top;
- add `procps-ng: procps`
> Adaptation/{ubuntu,debian}: install fix

- distro/adaptation/ubuntu
libmariadbclient18 package is now referred to the current&correct package libmariadb3
> distro/adaptation/ubuntu: Add libmariadb3 

- repo/linux/mptcp
MPTCP development has moved completely to mptcp@lists.linux.dev, so
don't email the old lists.01.org address any more.
> repo/linux/mptcp: Remove old mailing list

- monitors/mpstat
pkill follows "pattern" rather than "pid"
Fixes: 12863b154533779e575f3d25cf56fc37e027a5ac
> mpstat: Fix wrong usage of pkill

- bin/setup-local
Without nr_cpu in host file, I get this error
"unknown hash key: 'nr_cpu' hash"
Signed-off-by: Yihao Wu <wuyihao@linux.alibaba.com>
> Write nr_cpu in bin/setup-local

- monitors/cpuidle
cpuidle state name is not guaranteed spaceless,
eg "haltpoll idle". This lead to furthur issues.
Signed-off-by: Yihao Wu <wuyihao@linux.alibaba.com>
> Fix cpuidle state name with space

- tests/lmbench3
Suppose we have
/lkp/benchmarks/lmbench3/results/x86_64-linux-gnu/myhostname.0
..
/lkp/benchmarks/lmbench3/results/x86_64-linux-gnu/myhostname.9
Currently lkp always use myhostname.0 as the result file.
Fix this by removing the unneeded lmbench files, these files
are already duplicated by lkp anyway.
Signed-off-by: Yihao Wu <wuyihao@linux.alibaba.com>
> lmbench3: fix lmbench3 always return the first result

- repo/linux/ragnatech
I'm moving my tree to kernel.org.
Signed-off-by: Niklas Söderlund <niklas.soderlund@ragnatech.se>
> repo/linux: Update URL for ragnatech

- repo/linux/chrome-os
Add chromeos-5.15 to list of branches to test.
> repo/linux/chrome-os: Add chromeos-5.15

- repo/linux/ammarfaizi2-block
```
Hi,
Just a single commit for ammarfaizi2-block.
- Add mail_cc.
- Add owner.
- Add notify_build_success_branch.
Please pull.
----------------------------------------------------------------
The following changes since commit 9c5312b37523468acb5263d87c29eaf80e244abb:
repo/linux: add vbabka-slab (2022-01-10 11:32:24 +0800)
are available in the Git repository at:
git://github.com/ammarfaizi2/lkp-tests.git tags/ammarfaizi2-block-20220111
for you to fetch changes up to 978dd2ec6316563452d902e0ebf041c305691ace:
repo/linux: Update ammarfaizi2-block (2022-01-11 06:08:37 +0700)
----------------------------------------------------------------
ammarfaizi2-block-20220111
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>
----------------------------------------------------------------
Ammar …
```
> [GIT PULL] repo/linux: Update ammarfaizi2-block

- repo/linux/mptcp
Build success messages don't need to be sent to the mailing list.
----
Is there a way to send build success notifications only to the listed owners and not the mail_cc list, but still send the failures to all?
Just trying to reduce traffic to the mptcp mailing list.
> repo/linux/mptcp: Fewer email notifications

- repo/linux/ammarfaizi2-block
```
Hello,
Please pull one commit for ammarfaizi2-block.
Thanks!
repo/linux/ammarfaizi2-block: Update mail_cc
Viro reports that email to GNU/Weeb mailing list returned this
response:
"""
This is the mail system at host gnuweeb.org.
I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.
For further assistance, please send mail to postmaster.
If you do so, please include this problem report. You can
delete your own text from the attached returned message.
The mail system
<ml@gnuweeb.org> (expanded from <gwml@gnuweeb.org>): host
gnuweeb.org[private/dovecot-lmtp] said: 550 5.1.1 <ml@gnuweeb.org> User
doesn't exist: ml@gnuweeb.org (in reply to RCPT TO command)
"""
The cause is the mailing list address has recently changed. Fix …
```
> [GIT PULL] repo/linux/ammarfaizi2-block: Update mail_cc

- repo/linux/mptcp
This repository has a new branch for changes based on the net/master
branch, which also needs to be built & tested.
> repo/linux/mptcp: Also build & test the export-net branch

- repo/linux/ammarfaizi2-block
Hello,
Please pull 1 commit for ammarfaizi2-block to exclude Android branches from testing:
- Don't test Android branches. These branches are not for upstream. Make the build error private.
Ref: https://lore.kernel.org/lkml/87pmlzbyff.wl-maz@kernel.org
```
The following changes since commit b9a3e6c4ca5b236e393916821e92b807d7b947e0:
pkg/hackbench/PKGBUILD: update pkgver to 2.3 (2022-04-01 12:56:54 +0800)
are available in the Git repository at:
https://github.com/ammarfaizi2/lkp-tests.git tags/ammarfaizi2-block-20220402
for you to fetch changes up to 60471b2072ddf13338a7cc17927ce6606675c53f:
repo/linux/ammarfaizi2-block: Don't test Android branches (2022-04-02 17:26:19 +0700)
----------------------------------------------------------------
ammarfaizi2-block-20220402 …
```
> [GIT PULL] repo/linux/ammarfaizi2-block: Don't test Android branches

- repo/linux/chrome-platform
Add mail_to to Chrome Platform Group for chrome-platform.
Signed-off-by: Tzung-Bi Shih <tzungbi@kernel.org>
> repo/linux: add mail_to for chrome-platform

- repo/linux/rgushchin
I've switched to a @linux.dev account for the Linux kernel
development purposes. Update my email to send the lkp build results.
Signed-off-by: Roman Gushchin <roman.gushchin@linux.dev>
> repo: update my email

- repo/linux/tzungbi-chrome-platform
Update the config again so that it won't send build regression report to public.
Signed-off-by: Tzung-Bi Shih <tzungbi@kernel.org>
> repo/linux: update tzungbi-chrome-platform again

- jobs/blktests-nvme.yaml
- tests/blktests
blktests support nvme over rdma natively, this PR is trying to enable it.
https://github.com/osandov/blktests/blob/master/Documentation/running-tests.md#running-nvme-rdma-nvmeof-mp-srp-tests
> Enable blktests nvme over rdma

- distro/adaptation/centos
- distro/adaptation/fedora
- distro/adaptation/ubuntu-22.04
- pkg/hackbench/PKGBUILD
- pkg/rt-tests/PKGBUILD
1. Update rt-tests version.
2. This commit fixes hackbench install on:
adopting to right python libs package on rhel/centos/fedora
ubuntu 22-04: updating to right python package adoption
Signed-off-by: Srikanth Aithal <srikanth.aithal@amd.com>
> Fix hackbench install

- Gemfile.lock
- distro/debian
- distro/depends/lkp-dev
- distro/installer/debian
- distro/installer/ubuntu
Not add i386 arch on Debian/Ubuntu RISC-V port, otherwise it will cause
apt update fails every time.
Mark amd64/i386 arch only packages so the existing package filtering code
can work, these packages do not exist on RISC-V port.
Signed-off-by: Xin Zhang <xin.x.zhang@intel.com>
---
Hello maintainers,
- This patch is tested on SiFive HiFive Unmatched board running Ubuntu 22.04 RISC-V port. Debian sid RISC-V port should be mostly the same.
- Both Ubuntu 22.04 and Debian sid RISC-V port don't have ruby2 so I'm using rbenv to install ruby 2.7.6 globally.
- This patch is for fixing `sudo lkp install`.
- For each testcase there may be more dependency package changes, we may add them case by case later.
- It seems `distro/installer/$distro` and `distro/$distro` have duplicated install logic and …
> Fix RISC-V Debian/Ubuntu dependencies install

- distro/adaptation/ubuntu-22.04
libunwind-8 and libunwind-dev are not available on ubuntu 22.04
and causing perf and pmu-tools installation failed.
Updated to libunwind-14 and libunwind-14-dev to fix the installation
issue.
> update libunwind version for ubuntu22.04

- pkg/stream/PKGBUILD
stream is able to compile and run on riscv64.
> stream: add riscv support

- distro/adaptation-pkg/debian
- distro/adaptation-pkg/ubuntu
- jobs/coremark.yaml
- lib/stats.rb
- pkg/coremark/PKGBUILD
- spec/stats/coremark/01
- spec/stats/coremark/01.yaml
- stats/coremark
- tests/coremark
- tests/coremark.yaml
This is a test of EEMBC CoreMark processor benchmark that measure the
number of iteration per second of specific algorithms.
> coremark: add coremark benchmark

- pkg/hackbench/PKGBUILD
hackbench supports riscv64 architecture and able to run on riscv64 board.
> hackbench: add riscv64 support

- distro/adaptation-pkg/ubuntu
fio by default is not enable on ubuntu on lkp-tests, which causing
"fio: command not found" error when running the fio test on ubuntu.
distro/adaptation-pkg/ubuntu: added fio
> fio: enable fio test on ubuntu

- sbin/make.cross
By default, make.cross chooses GCC 9.3.0 rather than the latest
GCC 12.1.0 because the compiler list is sorted by ASCII:
gcc-10.2.0-nolibc
gcc-10.3.0-nolibc
...
gcc-11.3.0-nolibc
gcc-12.1.0-nolibc
gcc-4.9.4-nolibc
gcc-5.5.0-nolibc
...
gcc-9.3.0-nolibc
gcc-9.3.0-nolibc is picked up since it is listed last.
Use 'sort -V' for natual sort for versions:
gcc-4.9.4-nolibc
gcc-5.5.0-nolibc
...
gcc-9.3.0-nolibc
gcc-10.2.0-nolibc
gcc-10.3.0-nolibc
...
gcc-11.3.0-nolibc
gcc-12.1.0-nolibc
Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
> sbin/make.cross: choose the latest GCC correctly

- jobs/fio-basic-local-disk.yaml
- lib/fs_ext.sh
- setup/fio-setup-basic
- setup/fs
- Add 'format: n' parameter for fs will skip formatting of target partition
- Add support for fio tests to run on null block device
- Set fio testfile directory to /lkp/benchmarks/fio if target partition is local storage (root partition '/')
To support fio tests on local storage and null block device with new fio job file fio-basic-local-disk.yaml
> fio: add new job file for testing on local storage and enhancements for fio tests

- distro/adaptation/ubuntu
- distro/adaptation/ubuntu-22.04
update mapping for libgcrypt-dev and libipsec-mb
libgcrypt20-dev is available since ubuntu 18.04, libipsec-mb0 change to libipsec-mb1 since ubuntu 21.10
== fix issue ==
Use: /home/lkp-tests/distro/installer/ubuntu install libaio1 libapparmor1 libattr1 libbsd0 libcap2 libgcrypt20 libipsec-mb0 libjudydebian1 libkeyutils1 libsctp1 libaio-dev libapparmor-dev libattr1-dev libbsd-dev libcap-dev libgcrypt11-dev libipsec-mb-dev libjudy-dev libkeyutils-dev libsctp-dev linux-libc-dev zlib1g-dev Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB] Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB] Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB] Fetched 324 kB in 1s (251 kB/s) …
> stress-ng: fix install failed issue on ubuntu 22.04

- jobs/autonuma-benchmark.yaml
- tests/autonuma-benchmark
Couple of tweaks:
1. add variant to run both numa02_SMT and numa01_THREAD_ALLOC in single run.
2. die test if first iteration fails.
Signed-off-by: Srikanth Aithal <srikanth.aithal@amd.com>
> Tweak autonuma test

- distro/adaptation/redhat-8
- distro/adaptation/redhat-9
Currently perf dependencies fail to install
on rhel8.x and rhel9.x. This commit updates
dependencies.
Signed-off-by: Srikanth Aithal <srikanth.aithal@amd.com>
> Update dependencies for perf on redhat

- repo/linux/chrome-os
chromeos-4.4 is EOL. Stop testing it.
> repo/linux/chrome-os: Drop chromeos-4.4

- pkg/netperf/PKGBUILD
netperf supports riscv64 architecture and able to run on riscv64 qemu
patch config.guess to latest version to support riscv64
Signed-off-by: Kenny Gong <kenny.gong@intel.com>
> netperf: add riscv64 support

- repo/linux/conor
Since I am now taking patches for non-microchip contributions through my tree, it seems silly to keep the LKP reports private!
I looked, but admittedly not super hard, for documentation on the behaviour of the properties here.
I'd kinda like if I didn't spam people with the BUILD_SUCCESS emails for the branches with public reporting, but I am not sure how exactly to achieve that. For that reason, I've made this a draft.
> repo/linux/conor: enable public reporting for riscv branches

- spec/stats/schbench/01.yaml
- stats/schbench
Added changes to schbench stats to get the max and relative standard deviation of the end latency's between the iterations. Updated the spec/stats for the same.
Signed-off-by: Swapnil Sapkal <swapnil.sapkal@amd.com>
> Added changes to schbench stats in LKP

- repo/linux/matttbe-net-next
To receive notifications when updates are sent to this repository.
This repo is going to be used to validate patches from [MPTCP subsystem](https://github.com/intel/lkp-tests/blob/master/repo/linux/mptcp) to Netdev.
Thank you for running and maintaining this service!
> repo: add owner mail and notif for matttbe

- spec/stats/kernel-selftests/net-13
- spec/stats/kernel-selftests/net-13.yaml
- spec/stats/kernel-selftests/net-14
- spec/stats/kernel-selftests/net-14.yaml
- stats/kernel-selftests
For following output:
selftests: net: udpgro_fwd.sh
IPv4
No GRO                                  exec of "iptables-save" failed: No such file or directory
./udpgro_fwd.sh: line 135: [: !=: unary operator expected
exec of "iptables-save" failed: No such file or directory
./udpgro_fwd.sh: line 145: [: too many arguments
ok
GRO frag list                           exec of "iptables-save" failed: No such file or directory
./udpgro_fwd.sh: line 135: [: !=: unary operator expected
exec of "iptables-save" failed: No such file or directory
./udpgro_fwd.sh: line 145: [: too many arguments
ok
GRO fwd                                 exec of "iptables-save" failed: No such file or directory
./udpgro_fwd.sh: line 135: [: !=: unary operator expected
exec of "iptables-save" failed: No such file or …
> stats/kernel-selftests: add udpgro_fwd.sh process

- bin/setup-local
- distro/adaptation-pkg/amazon_linux
- lkp-exec/install
- pack/default
- sbin/pacman-LKP
Add amazon_linux distro to several places that have specialized code that deal with RPMs.
> amazon-linux: use same code as on fedora and centos

- spec/stats/kernel-selftests/x86-06
- spec/stats/kernel-selftests/x86-06.yaml
- stats/kernel-selftests
For following output:
selftests: x86: sigreturn_32
[OK]  set_thread_area refused 16-bit data
[OK]  set_thread_area refused 16-bit data
[WARN]        Could not find 64-bit CS
[SKIP]        Code segment unavailable for 64-bit CS, 32-bit SS
[RUN] Valid sigreturn: 32-bit CS (73), 32-bit SS (7b, GDT)
[OK]  all registers okay
Before this patch, json is:
x86.sigreturn_32.Valid_sigreturn_32-bit_CS_73_32-bit_SS_7b_GDT.pass: 1
After this patch, json is:
x86.sigreturn_32.Code_segment_unavailable_for_64-bit_CS_32-bit_SS.skip: 1 x86.sigreturn_32.Valid_sigreturn_32-bit_CS_73_32-bit_SS_7b_GDT.pass: 1
> stats/kernel-selftests: add x86/sigreturn_32/64 test result process

- spec/stats/kernel-selftests/x86-07
- spec/stats/kernel-selftests/x86-07.yaml
- spec/stats/kernel-selftests/x86-08
- spec/stats/kernel-selftests/x86-08.yaml
- stats/kernel-selftests
For following output:
selftests: x86: unwind_vdso_32
AT_SYSINFO is 0xf7f3e540
[OK]  AT_SYSINFO maps to linux-gate.so.1, loaded at 0x0xf7f3e000
[RUN] Set TF and check a fast syscall
In vsyscall at 0xf7f3e540, returning to 0xf7dfd0c7
SIGTRAP at 0xf7f3e540
0xf7f3e540
0xf7dfd0c7
[OK]    NR = 20, args = 1, 2, 3, 4, 5, 6
SIGTRAP at 0xf7f3e541
0xf7f3e541
0xf7dfd0c7
[FAIL]  NR = 3428, args = 1, 2, 3, 4, 5, 6
Before this patch, json is:
x86.unwind_vdso_32.Set_TF_and_check_a_fast_syscall.pass: 1
After this patch, json is:
x86.unwind_vdso_32.Set_TF_and_check_a_fast_syscall.fail: 1
Link: https://github.com/intel/lkp-tests/issues/207
> stats/kernel-selftests: add x86/unwind_vdso_32 test result process

- jobs/perf-bench-numa-mem.yaml
- spec/stats/perf-bench-numa-mem/01
- spec/stats/perf-bench-numa-mem/01.yaml
- tests/perf-bench-numa-mem
Currently perf numa mem bench runs with default params. This change adds support to change the number of processes and add extra set of parameters.
Added test for perf numa mem bench in spec/stats.
> Added support to run perf numa mem bench with custom params

- spec/unit_spec.rb
Add 12 rspec test examples to verify to_seconds function, including integer, float and string values
Closes #244
> spec/unit: add rspec test case for to_seconds

- stats/memtier
Refactored function gen_output_avg() to use a loop to reduce ABC Size.
Also refactored function gen_output_sum() to use loop as well.
Fixes #246
> rubocop: fix Metrics/AbcSize issue

- distro/adaptation/ubuntu-22.04
- docker/ubuntu/jammy/Dockerfile
Create new Dockerfile in docker/ubuntu/jammy to add support for ubuntu:22.04 image=ubuntu/jammy
Closes #267
> docker: support ubuntu:22.04

- repo/linux/martineau
- repo/linux/mptcp
I'm still using my git.kernel.org repo and am maintaining MPTCP, but my old email address doesn't work any more. Shift over to my kernel.org email.
> repo: Update contact email for Mat Martineau

- repo/linux/ieee1394-linux1394
At Linux kernel v6.4, the maintainer of Linux FireWire subsystem was replaced. This pull request brings changes related to it.
> repo/linux: replace maintainer of Linux FireWire subsystem

- bin/lkp-setup-rootfs
- lib/yaml.rb
2 patches here:
1- use YAML.unsafe_load to avoid ruby 3.2 / Psych 4 error
in `find': Tried to load unspecified class: Time (Psych::DisallowedClass)
from /usr/share/gems/gems/psych-5.0.1/lib/psych/class_loader.rb:28:in `load'
2- use single-quotes around grep 'pattern' since no variable interpolation is done.
Maybe wrong wrt escape-backslash, I had no success proving it either way.
> Fedora adapt

- repo/linux/matttbe-net-next
- repo/linux/mptcp
My other email address will bounce by the end of the year.
This email address is soon going to be updated in the `MAINTAINERS` file. For more details:
https://lore.kernel.org/netdev/20231004-send-net-20231004-v1-3-28de4ac663ae@kernel.org/
cc: @mjmartineau
> repo: update contact email for Matthieu Baerts

- pkg/rt-tests/PKGBUILD
- programs/hackbench/pkg/PKGBUILD
hackbench install fails currently as rt-tests
package is updated upstream. Fixing the version.
> Update rt-tests version

- README.md
When following README at "Run one atomic job", the output result for split-job is different. 
The following commands to install and run are updated as well to reflect the changes.
> README.md: Update output of split-job for hackbench.yaml

- distro/adaptation/centos-9
hackbench: install the remaining dependencies for the splited job, no packages available. fix for the following error:
[root@localhost lkp-tests]# lkp install ./hackbench-socket-8-threads-100%.yaml ......
未找到匹配的参数: default-jdk
未找到匹配的参数: libclang-dev
未找到匹配的参数: libmpfr6
未找到匹配的参数: libpfm4
未找到匹配的参数: libpfm4-dev
未找到匹配的参数: libpython3.9
未找到匹配的参数: libtraceevent1
未找到匹配的参数: libtraceevent-dev
未找到匹配的参数: llvm-dev
未找到匹配的参数: platform-python-devel.x86_64
未找到匹配的参数: python2-libs
未找到匹配的参数: python34
未找到匹配的参数: rng-tools5
未找到匹配的参数: python2
错误：没有任何匹配: default-jdk libclang-dev libmpfr6 libpfm4 libpfm4-dev libpython3.9 libtraceevent1 libtraceevent-dev llvm-dev platform-python-devel.x86_64 python2-libs python34 rng-tools5 python2 Cannot install some packages of perf-c2c depends
> distro/adaptation: fix hackbench package dependencies mapping of centos stream 9

- distro/adaptation/centos-7
hackbench: centos stream 9: no packages available when installing dependencies
> distro/adaptation: fix hackbench package dependencies of centos 7

- distro/adaptation/centos-9
will-it-scale-part1: install the remaining dependencies for the splited job, no packages available. fix for the following error: [root@localhost jobs]# lkp install ./will-it-scale-part1-thread-16-brk1.yaml ......
未找到匹配的参数: python2
软件包 zlib-devel-1.2.11-41.el9.x86_64 已安装。
错误：没有任何匹配: python2
Cannot install some packages of will-it-scale depends
> distro/adaptation: fix will-it-scale-part1 package dependencies mapping of centos 9

- distro/adaptation/centos-9
stress-ng-class-cpu-cache: install the remaining dependencies for the splited job, no packages available. fix for the following error: [root@localhost jobs]# lkp install ./stress-ng-class-cpu-cache-cpu-cache-100%-lockbus-60s.yaml ......
未找到匹配的参数: libipsec-mb0
未找到匹配的参数: libjudydebian1
未找到匹配的参数: libjudy-dev
错误：没有任何匹配: libipsec-mb0 libjudydebian1 libjudy-dev Cannot install some packages of stress-ng depends
> distro/adaptation: fix stress-ng-class-cpu-cache package dependencies mapping of centos 9

- repo/linux/jimc
Some of my branches are clones of Lukasz, somewhere in: https://chromium.googlesource.com/chromiumos/third_party/kernel
I'd like to not spam him with every branch I might push,
I've "noted" that with a trailing "# branch-match-pattern" on the mail-cc line, 
in case that can be made to operate (with some infrastructure patch?).
> jimc: add mail-cc for a collaborator

- repo/linux/mwalle
Add Michael Walles's mwalle/linux kernel.org repo.
> repo/linux: add mwalle

- lkp-exec/install
fix for the following error:
[root@localhost lkp-tests]# lkp install
Use: /root/lkp-tests/distro/installer/centos install bc gawk gzip kmod numactl rsync time which automake bison bsdtar bzip2 ca-certificates cpio fakeroot flex gcc git glibc-devel glibc-static glibc-devel.i686 glibc-static.i686 libtool make make automake gcc gcc-c++ kernel-devel rpm-build openssl openssl-devel patch perf perl-IPC-Run rsync ruby ruby-devel wget ...... 软件包 git-2.39.3-1.el9.x86_64 已安装。
软件包 glibc-devel-2.34-95.el9.x86_64 已安装。
未找到匹配的参数: glibc-static
未找到匹配的参数: glibc-static.i686
软件包 libtool-2.4.6-45.el9.x86_64 已安装。
......
软件包 openssl-1:3.0.7-25.el9.x86_64 已安装。
未找到匹配的参数: perl-IPC-Run
软件包 wget-1.21.1-7.el9.x86_64 已安装。
错误：没有任何匹配: glibc-static glibc-static.i686 perl-IPC-Run Cannot install some packages of lkp …
> lkp-exec/install: add OS version check and mirror source for centos

- distro/adaptation/debian-12
fix for the following error:
root@48d9c5df9663:~/lkp-tests# ./tools/test-packages.sh
arch=x86_64, distro=debian, _system_version=12
/root/lkp-tests/distro/installer/debian
Hit:1 http://linux-ftp.sh.intel.com/pub/mirrors/debian bookworm InRelease
Get:2 http://linux-ftp.sh.intel.com/pub/mirrors/debian bookworm/main i386 Packages [8679 kB]
Fetched 8679 kB in 2s (4884 kB/s)
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
Package python2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
dh-python
Package qemu is not available, but is referred to by another package.
This may mean …
> distro/adaption: update the package mapping of debian-12

- distro/adaptation/ubuntu-20.04
libpython3: install the remaining dependencies for the job, no packages available.
fix for the following error:
$ lkp install -f stream-10000000-10x-100-100%.yaml
......
Use: /opt/lkp-tests/distro/installer/ubuntu install binutils-dev bison clang default-jdk flex g++ gcc iproute2 libaudit-dev libbabeltrace-dev libc6-dev libcap-dev libclang-dev libdw1 libdw-dev libgtk2.0-dev libiberty-dev liblzma-dev libmpfr6 libnuma-dev libperl-dev libpfm4 libpfm4-dev libpython2.7 libpython3 libslang2-dev libssl-dev libunwind8 libunwind-dev libzstd-dev linux-tools-common llvm-dev make numactl patch python3 python3-dev python3-setuptools rng-tools5 sudo systemtap-sdt-dev xz-utils zlib1g-dev binutils-dev bison flex libaudit-dev libbabeltrace-dev libcap-dev libdw-dev libgtk2.0-dev libiberty-dev liblzma-dev …
> distro/adaptation: fix libpython3 package dependencies mapping of ubuntu

- distro/adaptation/ubuntu
Currently unixbench install fails on
Ubuntu 22.04.x throwing below error:
E: Unable to locate package libglut3
E: Unable to locate package libglut-dev
This commit updates those package dependency.
> Update unixbench dependency on ubuntu

- distro/adaptation/ubuntu-22.04
Currently kernbench install fails on ubuntu
22.04.x:
E: Unable to locate package libssl1.1
E: Couldn't find any package by glob 'libssl1.1'
E: Couldn't find any package by regex 'libssl1.1'
This commit updates the dependency for Ubuntu jammy
> Update libssl dependency for kernbench

- setup/fio-setup-basic
some fio parameters are not support on current lkp version, this PR is a improvement. Add some fio parameters: 'cpus_allowed_policy', 'cpus_allowed', 'offset_increment', and 'refill_buffers', these fio parameters are useful when we do IO performance benchmark test.
> Support more fio parameters

- distro/adaptation/ubuntu-20.04
libunwind: install the remaining dependencies for the job, no packages available.
fix for the following error:
$ lkp install -f stream-10000000-10x-100-100%.yaml
......
Use: /opt/lkp-tests/distro/installer/ubuntu install binutils-dev bison build-essential clang default-jdk flex iproute2 libaudit-dev libbabeltrace-dev libcap-dev libclang-dev libdw1 libdw-dev libgtk2.0-dev libiberty-dev liblzma-dev libmpfr6 libnuma-dev libperl-dev libpfm4 libpfm4-dev libpython2.7 libpython3.8 libslang2-dev libssl-dev libunwind libunwind-dev libzstd-dev linux-tools-common llvm-dev numactl patch python3 python3-dev python3-setuptools rng-tools5 sudo systemtap-sdt-dev xz-utils zlib1g-dev binutils-dev bison flex libaudit-dev libbabeltrace-dev libcap-dev libdw-dev libgtk2.0-dev libiberty-dev liblzma-dev …
> distro/adaptation: fix libunwind package dependencies mapping of ubuntu

- setup/fs
During ext4 filesystem performance test, we find newly formatted ext4 fs will create a lazyinit kernel thread in background, which will disturb fio performance test.
According to https://www.thomas-krenn.com/en/wiki/Ext4_Filesystem#Lazy_Initialization, it is better to disable lazyinit mechanism to make ext4 performance test result similar to workload in realworld.
For ext2, there is no lazyinit mechanism, so the format parameters for ext2 remain as before.
Signed-off-by: Yue Zhao <findns94@gmail.com>
> setup/fs: fix ext4 lazyinit performance issue

- spec/need_kconfig_format_spec.rb
Fix for issue #241 
* Check config format for need_kconfig part
* Format requirements:
1. Config name not start with CONFIG_
2. Config value only contain n, m, y, i386, x86_64, or empty
> Add rspec test to validate config format

- distro/installer/ubuntu
When trying to install the iperf3 package on Ubuntu Noble, it will
drop into an interactive mode asking if we should start iper3 as a
daemon automatically.
Avoid this by using the following command for apt command on Ubuntu:
yes "" | DEBIAN_FRONTEND=noninteractive
> distro/installer/ubuntu: avoid entering interactive mode

- distro/adaptation/ubuntu-24.04
Some packages like libpython2.7 are missing on Ubuntu Noble.
Create a new mapping to fix this issue.
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
> distro/adaptation: add mapping for 24.04

- distro/adaptation/ubuntu-24.04
This PR can resolve this issue: my OS version is Ubuntu 24.04, when I install lkp cases failed, error message is:
"The following packages have unmet dependencies:
libdw1 : Depends: libelf1 (= 0.176-1.1ubuntu0.1)
libdw1t64 : Breaks: libdw1 (< 0.190-1.1build4)
E: Unable to correct problems, you have held broken packages.
Cannot install some packages of perf-c2c depends ", please review, thanks.
> replace libdw1 to libdw1t64 on ubuntu-24.04

- repo/linux/chrome-os
I can pick up build reports from the mailing list, so drop the direct e-mails.
> repo/linux/chrome-os: Drop groeck@ from direct e-mails

- setup/fio-setup-basic
This commit can fix when /dev is not shown in `df` command in ubuntu 24.04.
When doing fio with raw disk, we should use `lsblk` to get disk capacity in bytes
instead of reading filesystem stats because raw disk will not mount filesystem
Fix for the following error:
"storage /dev/disk doesn't mounted" when doing fio with raw disk
> setup/fio-setup-basic: fix incorrect raw disk capacity calculation

- repo/linux/gmprice
- repo/linux/gourryinverse
Disassociating linux identify from company address, moving to forever-address.
> repo/linux: update test repo to forever-address

- programs/perf-bench-numa-mem/meta.yaml
- programs/perf-bench-numa-mem/run
1) Fix: lkp unable to pick latest perf rather using system's perf as a
consequence unable to run benchmarks on custom kernels
2) Feat: add new parameter # -thp_opt to enable lkp run two different
variant of the microbenchmark (thp/no_thp) and lkp ncompare able to
differentiate the results of the same
Reviewed-by: Srikanth Aithal <sraithal@amd.com>
> Fix lkp picking up system's perf and Add new param

- distro/adaptation/centos
Currently perf install fails citing few dependency failures on redhat 9.4. This commit fixes it.
Before fix:
```
Error: Unable to find a match: curl-minimal
Cannot install some packages of makepkg depends
..
Error: Unable to find a match: libcapstone-dev
Cannot install some packages of perf depends
..
-> Stripping unneeded symbols from binaries and libraries...
==> Creating package "perf"...
-> Generating .MTREE file...
/home/LKP/lkp-tests/sbin/makepkg: line 2337: bsdtar: command not found
-> Compressing package...
/home/LKP/lkp-tests/sbin/makepkg: line 2348: bsdtar: command not found
==> ERROR: Failed to create package file.
Install perf failed
```
After fix:
```
LINK    perf
GEN     python/perf.cpython-39-x86_64-linux-gnu.so
==> Entering fakeroot environment...
x86_64
==> Starting …
```
> Fix perf package dependencies on redhat

- programs/unixbench/pkg/unixbench.patch
Due to upstream unixbench changes, local unixbench patch apply was failing. This commit rebases the local unixbench patch to recent upstream version.
> Update local unixbench patch

- jobs/perf-bench-numa-mem.yaml
- programs/perf-bench-numa-mem/meta.yaml
- programs/perf-bench-numa-mem/run
Change thp options from thp/nothp to true/false in perf-bench-numa-mem's run script, to avoid ambiguity
> Simplify options for thp params

- programs/rt-tests/pkg/PKGBUILD
Fix rt-tests package md5sum.
Before fix:
```
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Source is https://www.kernel.org/pub/linux/utils/rt-tests/rt-tests-2.8.tar.gz
-> Found rt-tests-2.8.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with md5sums...
rt-tests-2.8.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
Install rt-tests failed
```
After fix:
```
-> Source is https://www.kernel.org/pub/linux/utils/rt-tests/rt-tests-2.8.tar.gz
-> Extracting rt-tests-2.8.tar.gz with bsdtar
==> Starting patch_source()...
PWD=/home/lkp-tests/tmp-pkg/hackbench/src, startdir=/home/lkp-tests/programs/hackbench/pkg, pkgname=hackbench, srcdir=/home/lkp-tests/tmp-pkg/hackbench/src
==> Entering …
```
> Fix rt-tests md5sum

- repo/linux/ssmalley-selinuxns
Enable testing of the in-progress SELinux namespaces support.
> repo/linux/ssmalley-selinuxns: add selinux namespaces branch

- lib/lkp_tmpdir.rb
- spec/log_cmd_spec.rb
Refactor spec/log_cmd_spec.sb to use LKP::TmpDir
Closes #427
> spec/log_cmd_spec.rb: refactor using LKP::TmpDir

- lib/result_root.rb
- lib/string.rb
- programs/igt/parse
- programs/iostat/parse
- programs/mpstat/parse
- programs/sar/parse
- programs/unixbench/parse
- programs/vmstat/parse
> refactor Time.parse to use String#to_time

- docker/README.md
- docker/test
> Add support for any in lkp docker install

- distro/adaptation/oracle
- docker/oraclelinux/Dockerfile
> docker support for oraclelinux/9

- spec/sort_remove_margin_spec.rb
> spec: test sort_remove_margin function

- spec/kernel_match_ver_spec.rb
> Create test for kernel_match_version function

- distro/adaptation/centos
- distro/adaptation/debian-10
- distro/adaptation/debian-11
- distro/adaptation/debian-12
- distro/adaptation/debian-trixie_sid
- distro/adaptation/fedora
- distro/adaptation/opensuse
- distro/adaptation/ubuntu-20.04
- distro/adaptation/ubuntu-22.04
- distro/adaptation/ubuntu-24.04
- programs/memtier/pkg/depends
- programs/memtier/pkg/depends-dev
> Change libevent-openssl-2 to libevent-openssl

- distro/adaptation/centos/default
- distro/adaptation/debian/12
- distro/adaptation/fedora/41
- distro/adaptation/fedora/default
- distro/adaptation/opensuse/default
- distro/adaptation/ubuntu/24.04
- programs/qemu-next/pkg/depends
> Replace libnfs13 to libnfs

- distro/adaptation/amazon_linux/2
- distro/adaptation/amazon_linux/2023
- distro/adaptation/amazon_linux/default
- distro/adaptation/centos/9
- distro/adaptation/debian/10
- distro/adaptation/debian/11
- distro/adaptation/debian/12
- distro/adaptation/debian/default
- distro/adaptation/debian/trixie_sid
- distro/adaptation/fedora/38
- distro/adaptation/fedora/41
- distro/adaptation/fedora/default
- distro/adaptation/ubuntu/20.04
- distro/adaptation/ubuntu/21.04
- spec/os_mapping_spec.rb
- Created spec test to check and remove duplicated lines between the default OS mapping and each OS-specific mappings
- Fix duplicated package in OS mapping file
Fix #484
> spec: test the integrity of distro/adaption files

- repo/linux/sophgo
As we are ready to maintain soc and rtc driver, add related branch for test. 
Also, to avoid potential conflict, change allowlist pattern.
> repo/linux/sophgo: add soc and rtc test branch

- programs/tbench/meta.yaml
- programs/tbench/parse
- programs/tbench/pkg
- programs/tbench/pkg/PKGBUILD
- programs/tbench/pkg/depends
- programs/tbench/pkg/depends-dev
- spec/stats/tbench/02
- spec/stats/tbench/02.yaml
The updated source URL for the dbench package that was introduced in 31dc80f82bd04 was causing a build error while attempting to install the tbench. In order to fix that, efforts to decouple tbench and dbench are taken.
The following changes are introduced in this commit:-
1) Decouple tbench and dbench such that tbench's pkg/ dir and
parse file unlink from dbench's
2) Change the source url from 'https://github.com/sahlberg/dbench'
to 'https://www.samba.org/ftp/tridge/dbench'
3) Add libtirpc-dev to tbench/depends-dev
4) Add unit tests under spec/stats
> Decouple tbench and dbench

- repo/linux/abelvesa
Add Abel Vesa's repo owner and integration branch.
> repo/linux/abelvesa: add owner and integration branch

- lib/tests/kernel-selftests.sh
Some logic in top-level Makefile in selftests can be missed when we only run sub-level Makefile (e.g. net selftests have the logic to automatically include net/lib in top-level Makefile in selftests). So this commit removes the logic to selectively run sub-level Makefile only and always runs top-level Makefile with the correct TARGETS.
Link: https://lore.kernel.org/oe-lkp/202505281004.6c3d0188-lkp@intel.com/
> kernel-selftests.sh: trigger top-level selftests Makefile when building

- distro/adaptation/centos/9
- lib/sysinfo.sh
Implement logic to calculate number of cores in LLC domain and use it to populate threads_to_iterate array.
Fix: will-it-scale installation issues on RHEL systems. Updating the python version in distro/adaptation seems to work good.
> Enhance sysinfo.sh to include nr_cores in LLC domain

- programs/hackbench/pkg/PKGBUILD
- programs/rt-tests/pkg/PKGBUILD
rt-tests package version has been updated from 2.8 -> 2.9 as its latest version in its source
"https://www.kernel.org/pub/linux/utils/rt-tests/". Hence updating the same in $pkgver of the build script for hackbench and rt-tests.
Signed-off-by: Suneeth D <Suneeth.D@amd.com>
Reviewed-by: Srikanth Aithal <sraithal@amd.com>
> Fix: rt-tests package version

- sbin/makepkg
The get_protocol function incorrectly identified URLs containing ".git" anywhere in the string as Git repositories, causing errors when downloading raw files. This commit updates the regex to match ".git$" (end of string).
> Fix Git URL parsing in get_protocol

- bin/run-local-monitor.sh
From
https://www.freedesktop.org/software/systemd/man/latest/os-release.html
the format of /etc/os-release file is shell variable like to support sourced in a shell script.  So, that is the best method to parse the file.
While the original method may include quote in the result variable, for example, for
$ cat /etc/os-release
...
ID="mydist"
...
we will get rootfs="mydist" with the original method, while we will get rootfs=mydist with shell source method.
So, use the shell source method to avoid the issue.
> bin/run-local-monitor.sh: Avoid to include quote in rootfs variable

- bin/run-local
- lib/common.rb
THP is disabled in ruby after version 2.6.  This will disable THP for job run by ruby too.  Enable THP when run job to avoid the issue.
> Avoid disabling THP when run job
