intel/lkp-tests

tests/fio, tests/fsmark
umount mounted dir after finish job
=> umount mounted dir after finish job

repo/linux/dennisszhou
I help maintain the percpu memory allocator and work on other parts of
the kernel too. Add my personal tree for developmental purposes.
Signed-off-by: Dennis Zhou <dennisszhou@gmail.com>
=> repo: dennisszhou add personal kernel tree

repo/linux/osandov
I contribute to Btrfs and the block layer, among others, so it'd be
great to stage stuff before it gets merged into those trees.
Signed-off-by: Omar Sandoval <osandov@osandov.com>
=> repo: add osandov's development tree

bin/run-local, bin/run-local.sh, lib/job.rb, lib/upload.sh, sbin/job2sh
lkp run accept atomic jobfile only
=> lkp run accept atomic jobfile only

repo/linux/lijiang-build
Signed-off-by: Lianbo Jiang <lijiang@redhat.com>
=> kernel patch build

repo/linux/nathanchance
I am going to be doing some changes that I would like more build
coverage on than I am able to provide myself.
=> repo: Add Nathan Chancellor's development tree

repo/linux/kuba-linux
I'm no longer at netronome, so direct the reports to my kernel email address.
=> Update my email in repo entry

repo/linux/linux-iv
Signed-off-by: Ionela Voinescu <ionela.voinescu@arm.com>
=> repo/linux: add linux-iv

repo/linux/chrome-os
=> repo/linux/chrome-os: add chromeos-5.10

distro/adaptation/archlinux, distro/adaptation/fedora, distro/adaptation/opensuse, distro/depends/lmbench3, pkg/lmbench3/Fix-rpc.h-not-found.patch
=> Fix two problems when install and run lmbench3 on Fedora 33

bin/lkp
=> bin/lkp: show the name of not found command

jobs/cgroup2-test.yaml, lib/stats.rb
=> jobs: add cgroup2 standalone testcase

distro/adaptation/fedora, distro/adaptation/opensuse
=> distro/adaptation: add package alias for fedora and opensuse

distro/adaptation/archlinux, distro/adaptation/centos, distro/adaptation/fedora, distro/adaptation/opensuse
=> distro/adaptation: add package alias for distros

distro/adaptation/ubuntu
Added `bsdtar: libarchive-tools` to `distro/adaptation/ubuntu`
=> Adaptation/ubuntu: "bsdtar : libarchive-tools"

distro/adaptation/centos, distro/adaptation/fedora
=> Add adaptation for Fedora

distro/adaptation/fedora
=> Fedora package adaptations

repo/linux/povik
Hello, test robot maintainers,
I would like to ask to have my personal repository watched by the test robot. I am developing some to-be-upstreamed drivers (Apple M1 audio support at the moment) there.
Thanks, Martin
=> repo/linux: add povik

distro/adaptation/fedora
Hello @rli9 
Thank you very much for the review.
I am sorry for the typo and have fixed it.
This is the v2 request to add some package adaptations for fedora.
=> [v2] Fedora package adaptations

repo/linux/l1k
Dear lkp maintainers,
please consider merging the below modifications to my repo spec.
I'd like to take the opportunity to thank you for the fantastic service you've provided over the past years. Fengguang added my repo in 2015 (without me even having to ask) and it's become an invaluable development tool for me. Seriously, you guys rock!
=> repo/linux/l1k: Mark repository private and enable build reports

repo/linux/tzungbi-chrome-platform
Signed-off-by: Tzung-Bi Shih <tzungbi@kernel.org>
=> repo/linux: update tzungbi-chrome-platform

repo/linux/krzk-dt
Add my new tree https://git.kernel.org/pub/scm/linux/kernel/git/krzk/linux-dt.git
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
=> repo/linux: Add krzk-dt tree

repo/linux/conor
Make the reports private & direct them via a +topic filter.
Signed-off-by: Conor Dooley <mail@conchuod.ie>
=> repo/linux: update conor

repo/linux/atomlin
Signed-off-by: Aaron Tomlin <atomlin@redhat.com>
=> repo/linux: add atomlin

jobs/schbench.yaml, tests/schbench, tests/schbench.yaml
Added iteration and additional params for schbench
Signed-off-by: Swapnil Sapkal <swapnil.sapkal@amd.com>
=> Added iteration and additional params for schbench

plot/plot-lmbench
plot/plot_lmbench: to plot a graph by combining 2 set of data.
Usage: plot_lmbench <data file 1> <data file 2>
=> lmbench3: add script for data analysis

jobs/stream.yaml, lib/statistics.rb, spec/stats/stream/01, spec/stats/stream/01.yaml, stats/stream, tests/stream
Modified stream benchmark to include:
1) Harmonic mean calculation
2) Included iterations and loop
Signed-off-by: Swapnil Sapkal <swapnil.sapkal@amd.com>
=> Added harmonic mean and changes to stream

tests/lz4
Signed-off-by: Kenny Gong <kenny.gong@intel.com>
=> refactor lz4 test script

distro/adaptation/centos, jobs/autonuma-benchmark.yaml, spec/stats/autonuma-benchmark/01, spec/stats/autonuma-benchmark/01.yaml, stats/autonuma-benchmark, tests/autonuma-benchmark
- Added iterations for autonuma-benchmark.
- Updated the dependancy in centos for autonuma-benchmark.
- Added the tests in spec/stats.
Signed-off-by: Swapnil Sapkal <swapnil.sapkal@amd.com>
=> Added iterations to autonuma-benchmark

repo/linux/brauner, repo/linux/vfs-idmapping
Signed-off-by: Christian Brauner (Microsoft) <brauner@kernel.org>
=> repo: update my current repo and add a new one

repo/linux/chrome-os
Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
=> repo/linux/chrome-os: add chromeos-6.1

distro/adaptation/amazon_linux-2, distro/adaptation/amazon_linux-2023, distro/installer/amazon_linux, lib/install.sh, lkp-exec/install
Signed-off-by: Sebastian Pop <spop@amazon.com>
=> add support for Amazon Linux 2

stats/kernel-selftests
=> Refactored KmodStater by taking out multiple test into own method.

stats/kernel-selftests
=> Refactor test result parsing in NetfilterStater class

stats/kernel-selftests
=> Refactor test result parsing in stats/VSDOStater class

stats/kernel-selftests
=> Refactor test result parsing in X86Stater class

stats/kernel-selftests
=> Refactor test result parsing in Stater class

stats/kernel-selftests
This PR simplifies the code for the VmallocStater class.
It targets issue #264.
=> Fix issue 264

pkg/hwsim/PKGBUILD
Update git repo link as previous repo link does not work
Fixes #287
=> hwsim: resolve git clone timeout

stats/perf-stat
=> Refactor calculations in calc_addon_keys method

distro/adaptation/fedora, docker/fedora/38/Dockerfile
=> Create new Dockerfile to add support for fedora:38

stats/perf-stat
=> Refactor parse method to fix rubocop issues

stats/perf-stat
=> Refactor output_interval method to fix rubocop issues

stats/kernel-selftests
=> Refactored ResctrlStater to fix rubocop issues

pkg/unixbench/unixbench.patch
Updating lkp unixbench patch inline with
upstream unixbench Makefile.
=> Update unixbench patch

repo/linux/song
Enable build test for branches in this repo.
=> repo/linux/song: Configure build test

bin/run-local, distro/adaptation/fedora
2 patches here:
fix split-job 'dirty file'
add adaptations for fedora package names.
=> Fedora adapt

repo/linux/gfs2, repo/linux/teigland-dlm
Sync with MAINTAINERS file. Refs:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7b7e3ed78ef7
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2938fd750e8b
=> Update contact info for gfs2 and dlm

programs/ebizzy/pkg/PKGBUILD, programs/unixbench/pkg/PKGBUILD
Update patch location for unixbench and
ebizzy to fix broken installation.
=> [lkp-tests PATCHv1] Minor patch update location

distro/adaptation/centos, distro/adaptation/ubuntu-22.04, jobs/tbench.yaml, programs/dbench/parse, programs/dbench/pkg/depends, programs/tbench/run, spec/stats/dbench/01, spec/stats/dbench/01.yaml, spec/stats/tbench/01, spec/stats/tbench/01.yaml
This commit:
1. updates tbench pkg dependecies
2. update error handling
3. updates stat parsing
4. introduces iterations
5. checks in UT cases for tbench and dbench
=> [lkp-tests PATCHv1] Fix tbench issues

repo/linux/andi-shyti, repo/linux/ashyti
Hi Philip,
Thanks for having added my repository. I am updating branches and repositories.
Thanks and best regards,
Andi
=> Update Andi Shyti's files

distro/adaptation/ubuntu
Update the JPEG runtime library name for ubuntu
=> Update stress-ng dependency on ubuntu jammy

programs/kernel-selftests/parse
Fixes #260
Original issue links file at `stats/kernel-selftests`, but it seems to have been moved to `programs/kernel-selftests/parse` since the issue has been created.
=> Resolve rubocop issues of CapabilitiesStater class

programs/kernel-selftests/parse
resolve #263 
PerceivedComplexity is resolved
CyclomaticComplexity is reduced from 15 to 9
The Cyclomatic Complexity is not able to reach 7 (the Robocop threshold), as the stat function is having 9 different conditions which is not combinable for further complexity reduction.
Acceptance test
=> Resolve ruboocop issues of BpfStater Class

programs/kernel-selftests/parse
=> Resolve Rubocop Metrics/BlockNesting issue

repo/linux/jimc
=> repo/jimc: update Lukasz email

repo/linux/amd-pstate
amd-pstate fixes and new content are staged on this tree.
=> Add https://git.kernel.org/pub/scm/linux/kernel/git/superm1/linux.git

repo/linux/sophgo
Add detail configuration for the test of linux/sophgo.
=> repo/linux/sophgo: add detail information

distro/adaptation-pkg/centos, distro/adaptation-pkg/debian, distro/adaptation-pkg/fedora, distro/adaptation-pkg/ubuntu, jobs/jitter.yaml, lib/stats.rb, programs/jitter/meta.yaml, programs/jitter/parse, programs/jitter/pkg/PKGBUILD, programs/jitter/run, spec/stats/jitter/01, spec/stats/jitter/01.yaml
- Add jitter test to lkp.
- Add testcase for the same in spec/stats.
Reviewed-and-tested-by: Srikanth Aithal <srikanth.aithal@amd.com>
=> Add jitter test to lkp

repo/linux/riteshharjani
Update branch and other details.
=> repo/riteshharjani: Update branch and other details

repo/linux/spacemit
Add SpacemiT's SoC kernel tree to LKP project,
Only for-next, fixes branches will be tested.
=> repo/linux: add spacemit

repo/linux/jpoimboe
=> repo/jpoimboe: update email

repo/linux/joel-granados, repo/linux/sysctl
=> Update contact for Joel's repos to kernel.org

lib/compare.rb
=> Resolve rubocop Naming/AccessorMethodName issue

lib/data_store.rb
=> lib/data_store.rb: resolve rubocop Naming/AccessorMethodName issue

lib/result_root.rb
=> Resolve Naming/AccessorMethodName for issue 402

programs/suspend/parse
=> Fix programs/suspend/parse: resolve rubocop Metrics/BlockNesting issue

lib/lkp_tmpdir.rb, spec/filter_need_kconfig_spec.rb
Refactor spec/filter_need_kconfig_spec.rb to use LKP::TmpDir
Add add_permission and remove_entry function in LKP::TmpDir
Closes #422
=> spec/filter_need_kconfig_spec.rb: refactor using LKP::TmpDir

lib/nresult_root.rb
=> lib/nresult_root.rb: Resolve rubocop Naming/AccessorMethodName issue

lib/lkp_tmpdir.rb, spec/filter_need_kernel_version_spec.rb
Refactor spec/filter_need_kernel_version_spec.sb to use LKP::TmpDir
Closes #423
=> spec/filter_need_kernel_version_spec.sb: refactor using LKP::TmpDir

distro/adaptation/fedora
=> distro/adaptation/fedora: add missing mapping to fedora packages

spec/filter_disk_spec.rb
Refactor spec/filter_need_kconfig_spec.rb to use LKP::TmpDir Added generate_job method
Closes #421
=> Refactor spec/filter_disk_spec.rb

spec/file_sorting_spec.rb
=> Add a rspec test to validate the file contents are sorted

distro/adaptation/opensuse, docker/README.md, docker/build, docker/opensuse/Dockerfile, lib/detect-system.sh, lkp-exec/install
=> Create Docker setup for opensuse/leap

spec/filter_need_memory_spec.rb
=> refactor spec/filter_need_memory_spec.rb

spec/filter_nr_threads_spec.rb
=> refactor spec/filter_nr_threads_spec.rb

spec/local_run_spec.rb
=> spec/local_run_spec.rb: refactor by using LKP::TmpDir

distro/adaptation/centos-9
=> distro/adaptation/centos: change mapping for centos package

bin/expand-job, filters/need_kconfig.rb, lib/array.rb, lib/compare.rb, lib/git/object.rb, lib/lkp_git.rb, programs/vm-scalability/parse, sbin/compare
=> Refactor size > 1 to .many

lib/stats.rb
=> refactor lib/stats.rb

programs/memtier/pkg/depends-dev
Fix for issue 401 - added dependency packages to memtier
=> Fix for issue 401

docker/README.md, docker/attach, lkp-exec/docker
Support lkp docker attach command which runs docker exec
Closes #453
=> docker: support lkp docker attach

distro/adaptation/amazon_linux, distro/adaptation/amazon_linux-2, distro/adaptation/amazon_linux-2022
=> amazon_linux cleanup

distro/adaptation/amazon_linux-2022, distro/installer/amazon_linux, docker/amazonlinux/Dockerfile
=> Create Docker setup for amazonlinux:2023

lib/common.rb, lib/dmesg.rb, lib/erb.rb, lib/string.rb, sbin/update-printk-error-messages, stats/time
=> refactor gsub(patterns, '') to use String#remove or String#remove!

docker/README.md, docker/rt, lkp-exec/docker, lkp-exec/rt
=> Add support for lkp docker rt

distro/adaptation/centos-9, lib/install.sh
=> Fix test-packages failure on oraclelinux/9

distro/adaptation/amazon_linux-2022, distro/adaptation/centos, distro/adaptation/centos-9, distro/adaptation/debian, distro/adaptation/fedora, distro/adaptation/opensuse, distro/adaptation/ubuntu, programs/perf/pkg/depends, programs/pmu-tools/pkg/depends
=> Rename libpfm4/libpfm4-dev to libpfm/libpfm-dev

docker/README.md, docker/build, docker/redhat/CentOS-8-Vault.repo, docker/redhat/Dockerfile
=> Enable redhat/ubi8 Docker image

distro/adaptation/opensuse/default
=> test-packages failure on opensuse/leap

monitors/no-stdout/sar
=> sar: fallback to system sar

programs/vm-scalability/run
The vm-scalability patch has been merged.
=> programs/vm-scalability/run: add timed_wp parameter
